{{- if .Values.notifications.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitwarden.fullname" . }}-notifications
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
spec:
  replicas: {{ .Values.notifications.replicaCount }}
  selector:
    matchLabels:
      {{- include "bitwarden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: notifications
  template:
    metadata:
      labels:
        {{- include "bitwarden.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: notifications
    spec:
      containers:
      - name: notifications
        image: "{{ .Values.notifications.image.repository }}:{{ default .Values.global.coreVersion .Values.notifications.image.tag }}"
        imagePullPolicy: {{ .Values.notifications.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ include "bitwarden.fullname" . }}-global-env
          - secretRef:
              name: {{ include "bitwarden.fullname" . }}-global-env
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        {{- if .Values.global.healthchecks }}
        livenessProbe:
          httpGet:
            path: /alive
            port: http
        readinessProbe:
          httpGet:
            path: /alive
            port: http
        {{- end }}
        {{- if .Values.global.resources }}
        resources:
{{ toYaml .Values.notifications.resources | indent 10 }}
        {{- end }}
      tolerations:
{{ toYaml .Values.notifications.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.notifications.affinity | indent 8 }}
{{- end }}
