{{- if and .Values.notifications.enabled .Values.notifications.pdb.enabled .Values.global.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bitwarden.fullname" . }}-notifications
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
spec:
  maxUnavailable: {{ .Values.notifications.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "bitwarden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: notifications
{{- end }}
