{{- if .Values.notifications.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitwarden.fullname" . }}-notifications
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
spec:
  type: {{ .Values.notifications.service.type }}
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bitwarden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
{{- end }}
