apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bitwarden.fullname" . }}-attachments
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: attachments
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.attachments.persistence.size | default "5Gi" | quote }}
  storageClassName: {{ .Values.attachments.persistence.storageClass | default "" | quote }}
