{{- if .Values.attachments.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitwarden.fullname" . }}-attachments
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: attachments
spec:
  type: {{ .Values.attachments.service.type }}
  ports:
    - port: 5000
      targetPort: attachments
      protocol: TCP
      name: attachments
  selector:
    {{- include "bitwarden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core
{{- end }}
