{{- if and .Values.mssql.enabled .Values.mssql.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bitwarden.fullname" . }}-mssql
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: mssql
spec:
  maxUnavailable: {{ .Values.mssql.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "bitwarden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mssql
{{- end }}
