{{- if or .Values.mssql.enabled .Values.attachments.enabled .Values.api.enabled .Values.admin.enabled .Values.identity.enabled .Values.notifications.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden.fullname" . }}-mssql-env
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: mssql
type: Opaque
data:
  SA_PASSWORD: {{ .Values.mssql.saPassword | b64enc | quote }}
{{- end }}
