{{- if or .Values.mssql.enabled .Values.attachments.enabled .Values.api.enabled .Values.admin.enabled .Values.identity.enabled .Values.notifications.enabled }}
{{ $fullName :=  include "bitwarden.fullname" . }}
{{ $connectionString := (printf "\"Data Source=tcp:%s-mssql,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=%s;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True\"" $fullName .Values.mssql.saPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden.fullname" . }}-mssql
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: mssql
type: Opaque
data:
  sa-password: {{ .Values.mssql.saPassword | b64enc | quote }}
  connection-string: {{ $connectionString | b64enc | quote }}
  global.override.env: {{ (printf "globalSettings__sqlServer__connectionString=%s\n" $connectionString ) | b64enc | quote }}
{{- end }}
