{{- if .Values.mssql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitwarden.fullname" . }}-mssql
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: mssql
spec:
  type: {{ .Values.mssql.service.type }}
  ports:
    - port: 1433
      targetPort: mssql
      protocol: TCP
      name: mssql
  selector:
    {{- include "bitwarden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mssql
{{- end }}
