{{- if .Values.identity.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden.fullname" . }}-identity
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
type: Opaque
data:
  identity.pfx: {{ .Values.identity.pfx | quote }}
  certificate-password: {{ .Values.identity.certificatePassword | b64enc | quote }}
{{- end }}
