{{- if .Values.identity.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitwarden.fullname" . }}-identity
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
spec:
  type: {{ .Values.attachments.service.type }}
  ports:
    - port: 5000
      targetPort: identity
      protocol: TCP
      name: identity
  selector:
    {{- include "bitwarden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: identity
{{- end }}
