{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitwarden.fullname" . }}-web
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "bitwarden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "bitwarden.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      annotations:
        checksum/web-config: {{ include (print $.Template.BasePath "/web/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: web
        image: "{{ .Values.web.image.repository }}:{{ default .Values.global.webVersion .Values.web.image.tag }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: web-config
          mountPath: /etc/bitwarden/web
        resources:
{{ toYaml .Values.web.resources | indent 10 }}
      volumes:
        - name: web-config
          configMap:
            name: {{ include "bitwarden.fullname" . }}-web
      tolerations:
{{ toYaml .Values.web.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.web.affinity | indent 8 }}
{{- end }}
