{{- if and .Values.web.enabled .Values.web.pdb.enabled .Values.global.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bitwarden.fullname" . }}-web
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  maxUnavailable: {{ .Values.web.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "bitwarden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
