{{- if and .Values.web.enabled .Values.web.vpa.enabled .Values.global.vpa }}
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "bitwarden.fullname" . }}-web
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bitwarden.fullname" . }}-web
  updatePolicy:
    updateMode: {{ .Values.web.vpa.updateMode | quote }}
{{- end }}
