{{- if and .Values.nginx.enabled .Values.nginx.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bitwarden.fullname" . }}-nginx
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  maxUnavailable: {{ .Values.nginx.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "bitwarden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
{{- end }}
