{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitwarden.fullname" . }}-nginx
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bitwarden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
{{- end }}
