apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitwarden.fullname" . }}-global-env
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
data:
  ASPNETCORE_ENVIRONMENT: Production
  globalSettings__selfHosted: "true"
  globalSettings__pushRelayBaseUri: https://push.bitwarden.com
  globalSettings__installation_identityUri: https://identity.bitwarden.com
  globalSettings__baseServiceUri__vault: https://{{ .Values.global.host }}
  globalSettings__baseServiceUri__internalVault: http://{{ include "bitwarden.fullname" . }}-web:5000
  globalSettings__baseServiceUri__api: https://{{ .Values.global.host }}/api
  globalSettings__baseServiceUri__internalApi: http://{{ include "bitwarden.fullname" . }}-api:5000
  globalSettings__baseServiceUri__identity: https://{{ .Values.global.host }}/identity
  globalSettings__baseServiceUri__internalIdentity: http://{{ include "bitwarden.fullname" . }}-identity:5000
  globalSettings__baseServiceUri__admin: https://{{ .Values.global.host }}/admin
  globalSettings__baseServiceUri__internalAdmin: http://{{ include "bitwarden.fullname" . }}-admin:5000
  globalSettings__baseServiceUri__notifications: https://{{ .Values.global.host }}/notifications
  globalSettings__baseServiceUri__internalNotifications: http://{{ include "bitwarden.fullname" . }}-notifications:80
  globalSettings__attachment__baseDirectory: /etc/bitwarden/core/attachments
  globalSettings__attachment__baseUrl: https://{{ .Values.global.host }}/attachments
  globalSettings__dataProtection__directory: /etc/bitwarden/core/aspnet-dataprotection
  globalSettings__logDirectory: /etc/bitwarden/core/logs
  globalSettings__licenseDirectory: /etc/bitwarden/core/licenses
