{{ $connectionString := (printf "\"Data Source=tcp:%s;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=%s;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True\"" (.Values.mssql.externalHostname | default (printf "%s-mssql,1433" (include "bitwarden.fullname" .)) ) .Values.mssql.saPassword) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden.fullname" . }}-global-env
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: global
type: Opaque
data:
  globalSettings__identityServer__certificatePassword: {{ .Values.identity.certificatePassword | b64enc | quote }}
  globalSettings__sqlServer__connectionString: {{ include "bitwarden.connectionString" . | b64enc | quote }}
  globalSettings__internalIdentityKey: {{ .Values.global.internalIdentityKey | b64enc | quote }}
  globalSettings__duo__aKey: {{ .Values.global.duoKey | b64enc | quote }}
  globalSettings__installation__id: {{ .Values.global.installationId | b64enc | quote }}
  globalSettings__installation__key: {{ .Values.global.installationKey | b64enc | quote }}
  globalSettings__yubico__clientId: {{ .Values.global.yubicoClientId | b64enc | quote }}
  globalSettings__yubico__key: {{ .Values.global.yubicoKey | b64enc | quote }}
  globalSettings__mail__replyToEmail: {{ .Values.global.mail.replyToEmail | b64enc | quote }}
  globalSettings__mail__smtp__host: {{ .Values.global.mail.host | b64enc | quote }}
  globalSettings__mail__smtp__username: {{ .Values.global.mail.username | b64enc | quote }}
  globalSettings__mail__smtp__password: {{ .Values.global.mail.password | b64enc | quote }}
  globalSettings__mail__smtp__ssl: {{ .Values.global.mail.ssl | b64enc | quote }}
  globalSettings__mail__smtp__port: {{ .Values.global.mail.port | b64enc | quote }}
  globalSettings__mail__smtp__useDefaultCredentials: {{ .Values.global.mail.useDefaultCredentials | b64enc | quote }}
  globalSettings__disableUserRegistration: {{ .Values.global.disableUserRegistration | b64enc | quote }}
  adminSettings__admins: {{ .Values.global.admins | b64enc | quote }}
