{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bitwarden.fullname" . }}-nginx
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
  annotations:
{{- if .Values.ingress.ip }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.ip | quote }}
{{- end }}
{{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
{{- end }}
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
spec:
  {{- if or .Values.certificates.enabled .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.host | quote }}
      secretName: {{ include "bitwarden.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.global.host | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "bitwarden.fullname" . }}-nginx
                port:
                  name: http
            path: /
            pathType: Prefix
{{- end -}}
