apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden.fullname" . }}-setup-env
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: mssql
type: Opaque
data:
  global.override.env: {{ (printf "globalSettings__sqlServer__connectionString=%s\n" ( include "bitwarden.connectionString" . ) ) | b64enc | quote }}