{{- if .Values.icons.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitwarden.fullname" . }}-icons
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: icons
spec:
  replicas: {{ .Values.icons.replicaCount }}
  selector:
    matchLabels:
      {{- include "bitwarden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: icons
  template:
    metadata:
      labels:
        {{- include "bitwarden.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: icons
    spec:
      containers:
      - name: icons
        image: "{{ .Values.icons.image.repository }}:{{ default .Values.global.coreVersion .Values.icons.image.tag }}"
        imagePullPolicy: {{ .Values.icons.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        {{- if .Values.global.healthchecks }}
        livenessProbe:
          httpGet:
            path: /google.com/icon.png
            port: http
        readinessProbe:
          httpGet:
            path: /google.com/icon.png
            port: http
        {{- end }}
        {{- if .Values.global.resources }}
        resources:
{{ toYaml .Values.icons.resources | indent 10 }}
        {{- end }}
      tolerations:
{{ toYaml .Values.icons.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.icons.affinity | indent 8 }}
{{- end }}
