{{- if and .Values.icons.enabled .Values.icons.pdb.enabled .Values.global.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bitwarden.fullname" . }}-icons
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: icons
spec:
  maxUnavailable: {{ .Values.icons.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "bitwarden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: icons
{{- end }}
