{{- if and .Values.icons.enabled .Values.icons.vpa.enabled .Values.global.vpa }}
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "bitwarden.fullname" . }}-icons
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: icons
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bitwarden.fullname" . }}-icons
  updatePolicy:
    updateMode: {{ .Values.icons.vpa.updateMode | quote }}
{{- end }}
