{{- if or .Values.attachments.enabled .Values.api.enabled .Values.admin.enabled .Values.identity.enabled }}
{{- if .Values.core.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bitwarden.fullname" . }}-core
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  accessModes:
    - {{ .Values.core.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.core.persistence.size | quote }}
{{- if .Values.core.persistence.storageClass }}
{{- if (eq "-" .Values.core.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.core.persistence.storageClass | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
