{{- if or .Values.attachments.enabled .Values.api.enabled .Values.admin.enabled .Values.identity.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bitwarden.fullname" . }}-core
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  selector:
    matchLabels:
      {{- include "bitwarden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: core
  serviceName: {{ include "bitwarden.fullname" . }}-core
  template:
    metadata:
      labels:
        {{- include "bitwarden.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: core
      annotations:
        checksum/identity-secret: {{ include (print $.Template.BasePath "/identity/secret.yaml") . | sha256sum }}
        {{- if .Values.setup.enabled }}
        checksum/mssql-secret: {{ include (print $.Template.BasePath "/mssql/secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      containers:
      {{- if .Values.attachments.enabled }}
      - name: attachments
        image: "{{ .Values.attachments.image.repository }}:{{ default .Values.global.coreVersion .Values.attachments.image.tag }}"
        imagePullPolicy: {{ .Values.attachments.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:5001"
{{ include "bitwarden.global" . | indent 8 }}
        ports:
        - name: attachments
          containerPort: 5001
          protocol: TCP
        volumeMounts:
        - name: core-data
          mountPath: /etc/bitwarden/core/attachments
          subPath: attachments
          readOnly: true
        livenessProbe:
          httpGet:
            path: /alive
            port: attachments
        readinessProbe:
          httpGet:
            path: /alive
            port: attachments
        resources:
{{ toYaml .Values.attachments.resources | indent 10 }}
      {{- end }}
      {{- if .Values.api.enabled }}
      - name: api
        image: "{{ .Values.api.image.repository }}:{{ default .Values.global.coreVersion .Values.api.image.tag }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:5002"
{{ include "bitwarden.global" . | indent 8 }}
        ports:
        - name: api
          containerPort: 5002
          protocol: TCP
        volumeMounts:
        - name: core-data
          mountPath: /etc/bitwarden/core
{{/*        livenessProbe:*/}}
{{/*          httpGet:*/}}
{{/*            path: /alive*/}}
{{/*            port: api*/}}
{{/*          initialDelaySeconds: 30*/}}
{{/*          periodSeconds: 15*/}}
{{/*        readinessProbe:*/}}
{{/*          httpGet:*/}}
{{/*            path: /alive*/}}
{{/*            port: api*/}}
{{/*          initialDelaySeconds: 30*/}}
{{/*          periodSeconds: 15*/}}
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
      {{- end }}
      {{- if .Values.identity.enabled }}
      - name: identity
        image: "{{ .Values.identity.image.repository }}:{{ default .Values.global.coreVersion .Values.identity.image.tag }}"
        imagePullPolicy: {{ .Values.identity.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:5003"
{{ include "bitwarden.global" . | indent 8 }}
        ports:
        - name: identity
          containerPort: 5003
          protocol: TCP
        volumeMounts:
        - name: core-data
          mountPath: /etc/bitwarden/core
        - name: identity-conf
          mountPath: /etc/bitwarden/identity
{{/*        livenessProbe:*/}}
{{/*          httpGet:*/}}
{{/*            path: /.well-known/openid-configuration*/}}
{{/*            port: identity*/}}
{{/*          initialDelaySeconds: 60*/}}
{{/*          periodSeconds: 15*/}}
{{/*        readinessProbe:*/}}
{{/*          httpGet:*/}}
{{/*            path: /.well-known/openid-configuration*/}}
{{/*            port: identity*/}}
{{/*          initialDelaySeconds: 60*/}}
{{/*          periodSeconds: 15*/}}
        resources:
{{ toYaml .Values.identity.resources | indent 10 }}
      {{- end }}
      {{- if .Values.admin.enabled }}
      - name: admin
        image: "{{ .Values.admin.image.repository }}:{{ default .Values.global.coreVersion .Values.admin.image.tag }}"
        imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:5004"
{{ include "bitwarden.global" . | indent 8 }}
        ports:
        - name: admin
          containerPort: 5004
          protocol: TCP
        volumeMounts:
        - name: core-data
          mountPath: /etc/bitwarden/core
{{/*        livenessProbe:*/}}
{{/*          httpGet:*/}}
{{/*            path: /*/}}
{{/*            port: admin*/}}
{{/*          initialDelaySeconds: 60*/}}
{{/*          periodSeconds: 15*/}}
{{/*        readinessProbe:*/}}
{{/*          httpGet:*/}}
{{/*            path: /*/}}
{{/*            port: admin*/}}
{{/*          initialDelaySeconds: 60*/}}
{{/*          periodSeconds: 15*/}}
        resources:
{{ toYaml .Values.admin.resources | indent 10 }}
      {{- end }}
      initContainers:
      {{- if .Values.setup.enabled }}
      - name: setup
        image: "{{ .Values.setup.image.repository }}:{{ default .Values.global.coreVersion .Values.setup.image.tag }}"
        imagePullPolicy: {{ .Values.setup.image.pullPolicy }}
        command: ["sh", "-c", "dotnet Setup.dll -update 1 -db 1 -os lin -corev $COREVERSION -webv $WEBVERSION"]
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: COREVERSION
          value: {{ .Values.global.coreVersion }}
        - name: WEBVERSION
          value: {{ .Values.global.webVersion }}
{{ include "bitwarden.global" . | indent 8 }}
        volumeMounts:
        - name: core-data
          mountPath: /etc/bitwarden/core
        - name: setup-conf
          mountPath: /bitwarden/env
        resources:
{{ toYaml .Values.setup.resources | indent 10 }}
      {{- end }}
      volumes:
      - name: core-data
      {{- if .Values.core.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "bitwarden.fullname" . }}-core
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.identity.enabled }}
      - name: identity-conf
        secret:
          secretName: {{ include "bitwarden.fullname" . }}-identity
          items:
            - key: identity.pfx
              path: identity.pfx
      {{- end }}
      {{- if .Values.setup.enabled }}
      - name: setup-conf
        secret:
          secretName: {{ include "bitwarden.fullname" . }}-mssql
          items:
            - key: global.override.env
              path: global.override.env
      {{- end }}
      tolerations:
{{ toYaml .Values.core.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.core.affinity | indent 8 }}
{{- end }}
